name: franz
description: Dart library using librdkafka via FFI
version: 0.3.0
repository: https://github.com/marianhlavac/franz

environment:
  sdk: ^3.7.2

dependencies:
  ffi: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  ffigen: ^19.0.0
  lints: ^5.1.1
  test: ^1.24.0

platforms:
  linux:
  macos:
  windows:

ffigen:
  output: "lib/librdkafka/generated_bindings.g.dart"
  name: LibRdKafka
  headers:
    entry-points:
      - "vendor/rdkafka.h"
