name: franz
description: A starting point for Dart libraries or applications.
version: 0.1.1
repository: https://github.com/marianhlavac/franz

environment:
  sdk: ^3.4.0

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  ffigen: ^12.0.0
  lints: ^3.0.0
  test: ^1.24.0

ffigen:
  output: "lib/librdkafka/generated_bindings.dart"
  name: LibRdKafka
  headers:
    entry-points:
      - "vendor/librdkafka/rdkafka.h"
